runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: .*
  static_files: index.html
  upload: index\.html

skip_files:
- .git*
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.md
- ^(.*/)?.*\.rb
- tmp
- ^(.*/)?.*\.sass-cache
- README.md
- .gitignore
- .*.json
